/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#40000d",
        "tertiary-fixed-dim": "#ffb2b7",
        "on-secondary-fixed": "#000767",
        "outline-variant": "#c7c4d8",
        "on-tertiary-fixed-variant": "#92002a",
        "inverse-primary": "#c3c0ff",
        "on-primary-container": "#dad7ff",
        "background": "#faf8ff",
        "on-primary-fixed": "#0f0069",
        "secondary": "#4953bc",
        "on-secondary-fixed-variant": "#2f3aa3",
        "outline": "#777587",
        "surface-variant": "#dae2fd",
        "primary": "#3525cd",
        "primary-fixed": "#e2dfff",
        "surface-container-highest": "#dae2fd",
        "surface-tint": "#4d44e3",
        "on-secondary-container": "#17228f",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "surface-container-high": "#e2e7ff",
        "tertiary-container": "#bf0f3c",
        "on-background": "#131b2e",
        "tertiary": "#95002b",
        "error": "#ba1a1a",
        "tertiary-fixed": "#ffdadb",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#c3c0ff",
        "on-surface-variant": "#464555",
        "surface-bright": "#faf8ff",
        "surface": "#faf8ff",
        "secondary-container": "#8792fe",
        "on-primary-fixed-variant": "#3323cc",
        "secondary-fixed": "#e0e0ff",
        "surface-container": "#eaedff",
        "surface-dim": "#d2d9f4",
        "secondary-fixed-dim": "#bdc2ff",
        "inverse-surface": "#283044",
        "inverse-on-surface": "#eef0ff",
        "on-tertiary-container": "#ffd0d2",
        "primary-container": "#4f46e5",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#131b2e",
        "surface-container-low": "#f2f3ff",
        brand: {
          50: '#F5F3FF',
          100: '#EDE9FE',
          200: '#DDD6FE',
          300: '#C4B5FD',
          400: '#A78BFA',
          500: '#8B5CF6',
          600: '#7C3AED',
          700: '#6D28D9',
          800: '#5B21B6',
          900: '#4C1D95',
        },
        kairos: {
          surface: '#F8F9FC',
          bubble: '#3B28CC',
          subtle: '#F0F2F9'
        }
      },
      boxShadow: {
        'card': '0 4px 20px -2px rgba(99, 102, 241, 0.05), 0 2px 6px -1px rgba(0, 0, 0, 0.02)',
        'float': '0 12px 32px -4px rgba(79, 70, 229, 0.12), 0 4px 12px -2px rgba(0, 0, 0, 0.04)',
        'glow': '0 0 24px -2px rgba(147, 51, 234, 0.35)',
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-lg": "1.25rem",
        "gutter-mobile": "1rem",
        "space-sm": "0.75rem",
        "dock-safe-inset": "5.5rem",
        "space-2xs": "0.25rem",
        "space-3xl": "2.5rem",
        "space-2xl": "2rem",
        "gutter-desktop": "1.5rem",
        "space-4xl": "3rem",
        "space-md": "1rem",
        "space-xl": "1.5rem",
        "space-xs": "0.5rem"
      },
      fontFamily: {
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "metric-numeral": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["10px", { lineHeight: "12px", letterSpacing: "0.04em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "metric-numeral": ["24px", { lineHeight: "28px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.025em", fontWeight: "800" }],
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
};
