/**
 * Kairos Service Worker Registration
 * 
 * Registers the production PWA service worker with auto-update capability.
 * Safely handles environments where service workers are not supported or in local dev.
 */

export function registerSW(): void {
  if (typeof window !== 'undefined' && 'serviceWorker' in navigator) {
    window.addEventListener('load', () => {
      // Register sw.js generated by vite-plugin-pwa (or workbox)
      navigator.serviceWorker
        .register('/sw.js', { scope: '/' })
        .then((registration) => {
          // Check for service worker updates periodically
          setInterval(() => {
            registration.update().catch(() => {});
          }, 60 * 60 * 1000); // Hourly check

          registration.onupdatefound = () => {
            const installingWorker = registration.installing;
            if (installingWorker) {
              installingWorker.onstatechange = () => {
                if (installingWorker.state === 'installed' && navigator.serviceWorker.controller) {
                  // New content is available and will be used when all tabs are closed
                  console.log('[Kairos PWA] New update installed and ready.');
                }
              };
            }
          };
        })
        .catch((err) => {
          console.debug('[Kairos PWA] Service worker registration skipped:', err);
        });
    });
  }
}
